#!/usr/bin/env python3
"""Generate a machine-readable inventory of the experimental data in ``docs/``.

The induction-furnace project accumulated ~100 logged anneal runs plus SEM/optical
characterization. This script summarizes what exists (run IDs, materials, soak
temperature/time parsed from the file names, file types, and characterization
assets) into ``paper/journal-assessment/DATA_INVENTORY.md`` so the question
"is there enough data for a traditional journal paper without new experiments?"
can be answered from version-controlled context.

The script is read-only with respect to ``docs/`` and idempotent.

Usage::

    python paper/build_data_inventory.py
"""
from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DOCS = REPO / "docs"
OUT = HERE / "journal-assessment" / "DATA_INVENTORY.md"

# e.g. "1200C_12h", "1400C_10min", "1325C_40h"
COND_RE = re.compile(r"(\d{3,4})\s*C[_\- ]*(\d+\.?\d*)\s*(h|min)", re.IGNORECASE)
MATERIALS = ("Ni200", "Ni4N5", "Pd", "YSZ", "crucible", "evap")


def parse_runs() -> list[dict]:
    data_log = DOCS / "data_log"
    rows: list[dict] = []
    if not data_log.exists():
        return rows
    for p in sorted(data_log.rglob("*")):
        if not p.is_file():
            continue
        name = p.name
        mat = next((m for m in MATERIALS if m.lower() in name.lower()), "")
        cond = COND_RE.search(name)
        temp = int(cond.group(1)) if cond else None
        soak = f"{cond.group(2)}{cond.group(3).lower()}" if cond else ""
        rows.append({
            "rel": str(p.relative_to(DOCS)),
            "name": name,
            "material": mat,
            "temp_C": temp,
            "soak": soak,
            "ext": p.suffix.lower().lstrip("."),
        })
    return rows


def fmt_table(rows: list[dict]) -> str:
    keep = [r for r in rows if r["temp_C"] or r["material"]]
    lines = ["| Run / file | Material | Soak T (°C) | Soak time | Type |",
             "|------------|----------|------------:|-----------|------|"]
    for r in sorted(keep, key=lambda r: r["rel"]):
        lines.append(f"| {r['rel']} | {r['material'] or '—'} | "
                     f"{r['temp_C'] or '—'} | {r['soak'] or '—'} | {r['ext']} |")
    return "\n".join(lines)


def characterization_assets() -> list[str]:
    out = []
    for rel in ("student-work/RyanWeber.pdf",
                "equipment-reference",
                "ThermalEvaporation"):
        p = DOCS / rel
        if p.exists():
            if p.is_dir():
                n = sum(1 for _ in p.rglob("*") if _.is_file())
                out.append(f"- `docs/{rel}/` — {n} file(s)")
            else:
                out.append(f"- `docs/{rel}` — {p.stat().st_size // 1024} KB")
    return out


def main() -> None:
    rows = parse_runs()
    mats = Counter(r["material"] for r in rows if r["material"])
    temps = sorted({r["temp_C"] for r in rows if r["temp_C"]})
    by_ext = Counter(r["ext"] for r in rows)
    # group run IDs by material
    runs_by_mat: dict[str, set[str]] = defaultdict(set)
    for r in rows:
        m = re.search(r"IFrun\d+", r["name"], re.IGNORECASE)
        if m and r["material"]:
            runs_by_mat[r["material"]].add(m.group(0))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    md = ["# Experimental data inventory (auto-generated)",
          "",
          "Generated by `paper/build_data_inventory.py` from the binary data files in",
          "`docs/`. This summarizes what already exists **without any new experiments**,",
          "to assess feasibility of a traditional (non-HardwareX) journal contribution.",
          "",
          "## Summary",
          "",
          f"- **Total files under `docs/data_log/`:** "
          f"{sum(1 for _ in (DOCS / 'data_log').rglob('*') if _.is_file())}",
          f"- **Files with a parseable material/condition label:** {len(rows)}",
          f"- **Materials (by labeled file count):** "
          + ", ".join(f"{k} ({v})" for k, v in mats.most_common()),
          f"- **Soak temperatures observed (°C):** "
          + ", ".join(str(t) for t in temps),
          f"- **Data file types:** "
          + ", ".join(f"{k or 'none'} ({v})" for k, v in by_ext.most_common()),
          "",
          "### Distinct run IDs by material",
          ""]
    for mat, ids in sorted(runs_by_mat.items()):
        md.append(f"- **{mat}:** {len(ids)} runs — "
                  + ", ".join(sorted(ids)))
    md += ["",
           "## Characterization / supporting assets",
           "",
           *characterization_assets(),
           "",
           "## Labeled runs (material + soak condition parsed from filename)",
           "",
           fmt_table(rows),
           ""]
    OUT.write_text("\n".join(md))
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} labeled files)")


if __name__ == "__main__":
    main()
